### ISSUE TITLE
[Design/FE] 신규 기능에 대한 디자인 제작 및 기존 디자인을 통일성 있게 수정한다.

### ISSUE THREAD

**Issue by PortalCube** [sync-without-async/CapstoneDesign-FrontEnd#7]
### Description
캡스톤 버전에서 추가될 새로운 기능에 대한 디자인을 제작하고, 프로토타입 버전 기능들의 디자인을 수정합니다.

### In Progress
상세 내용은 추후 결정

**Comment by osohyun0224** [comment]
새로운 디자인 이슈 생성으로 해당 이슈를 닫겠습니다.
